name: generate-builds
on:
  push:
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  generate-soh-otr:
    runs-on: ${{ (vars.LINUX_RUNNER && fromJSON(vars.LINUX_RUNNER)) || 'ubuntu-latest' }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{ runner.os }}-soh-otr-ccache
    - name: Debug apt-deps.txt
      if: ${{ !vars.LINUX_RUNNER }}
      run: |
        cat .github/workflows/apt-deps.txt
    - name: Check Python
      if: ${{ !vars.LINUX_RUNNER }}
      run: |
        python3 --version
    - name: Install dependencies
      if: ${{ !vars.LINUX_RUNNER }}
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libbz2-dev python3-dev zlib1g-dev libboost-all-dev $(cat .github/workflows/apt-deps.txt)
    - name: Check Boost version
      if: ${{ !vars.LINUX_RUNNER }}
      run: |
        apt-cache policy libboost-all-dev
    - name: Install latest SDL
      if: ${{ !vars.LINUX_RUNNER }}
      run: |
        export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
        wget https://www.libsdl.org/release/SDL2-2.26.1.tar.gz
        tar -xzf SDL2-2.26.1.tar.gz
        cd SDL2-2.26.1
        ./configure
        make -j 10
        sudo make install
        sudo cp -av /usr/local/lib/libSDL* /lib/x86_64-linux-gnu/
    - name: Generate soh.otr
      run: |
        export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
        cmake --no-warn-unused-cli -H. -Bbuild-cmake -GNinja -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON
        cmake --build build-cmake --config Release --target GenerateSohOtr --verbose
    - uses: actions/upload-artifact@v4
      with:
        name: soh.otr
        path: soh.otr
        retention-days: 1
  build-linux:
    needs: generate-soh-otr
    strategy:
      fail-fast: true
      matrix:
        include:
        - os: ubuntu-20.04
          gcc: 10
          archive-suffix: compatibility
        - os: ubuntu-22.04
          gcc: 12
          archive-suffix: performance
    runs-on: ${{ (matrix.os == 'ubuntu-20.04' && ((vars.LINUX_COMPATIBILITY_RUNNER && fromJSON(vars.LINUX_COMPATIBILITY_RUNNER)) || matrix.os)) || (matrix.os == 'ubuntu-22.04' && ((vars.LINUX_PERFORMANCE_RUNNER && fromJSON(vars.LINUX_PERFORMANCE_RUNNER)) || matrix.os)) }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Debug system
      run: |
        uname -a
        cmake --version
        ninja --version
        curl --version
    - name: Install dependencies
      if: ${{ (matrix.os == 'ubuntu-20.04' && !vars.LINUX_COMPATIBILITY_RUNNER) || (matrix.os == 'ubuntu-22.04' && !vars.LINUX_PERFORMANCE_RUNNER) }}
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libbz2-dev python3-dev zlib1g-dev libboost-all-dev gcc-${{ matrix.gcc }} g++-${{ matrix.gcc }} $(cat .github/workflows/apt-deps.txt)
    - name: Debug compilers
      run: |
        gcc --version
        g++ --version
        gcc-${{ matrix.gcc }} --version
        g++-${{ matrix.gcc }} --version
    - name: Check Boost version
      if: ${{ (matrix.os == 'ubuntu-20.04' && !vars.LINUX_COMPATIBILITY_RUNNER) || (matrix.os == 'ubuntu-22.04' && !vars.LINUX_PERFORMANCE_RUNNER) }}
      run: |
        apt-cache policy libboost-all-dev
        dpkg -L libboost-all-dev | grep include/boost
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{ matrix.os }}-ccache
    - name: Install latest SDL
      if: ${{ (matrix.os == 'ubuntu-20.04' && !vars.LINUX_COMPATIBILITY_RUNNER) || (matrix.os == 'ubuntu-22.04' && !vars.LINUX_PERFORMANCE_RUNNER) }}
      run: |
        export PATH="/usr/lib/ccache:$PATH"
        wget https://www.libsdl.org/release/SDL2-2.26.1.tar.gz
        tar -xzf SDL2-2.26.1.tar.gz
        cd SDL2-2.26.1
        ./configure
        make -j 10
        sudo make install
        sudo cp -av /usr/local/lib/libSDL* /lib/x86_64-linux-gnu/
    - name: Install latest SDL_net
      if: ${{ (matrix.os == 'ubuntu-20.04' && !vars.LINUX_COMPATIBILITY_RUNNER) || (matrix.os == 'ubuntu-22.04' && !vars.LINUX_PERFORMANCE_RUNNER) }}
      run: |
        export PATH="/usr/lib/ccache:$PATH"
        wget https://www.libsdl.org/projects/SDL_net/release/SDL2_net-2.2.0.tar.gz
        tar -xzf SDL2_net-2.2.0.tar.gz
        cd SDL2_net-2.2.0
        ./configure
        make -j 10
        sudo make install
        sudo cp -av /usr/local/lib/libSDL* /lib/x86_64-linux-gnu/
    - name: Download soh.otr
      uses: actions/download-artifact@v4
      with:
        name: soh.otr
    - name: Build SoH
      run: |
        export PATH="/usr/lib/ccache:$PATH"
        for i in {1..3}; do
          cmake --no-warn-unused-cli -H. -Bbuild-cmake -GNinja -DCMAKE_BUILD_TYPE:STRING=Release -DBUILD_REMOTE_CONTROL=1 -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON && break
          echo "CMake failed, retrying ($i/3)..."
          sleep 5
        done
        cmake --build build-cmake --config Release -j3 --verbose
        (cd build-cmake && cpack -G External)
        mv README.md readme.txt
        mv build-cmake/*.appimage soh.appimage
      env:
        CC: gcc-${{ matrix.gcc }}
        CXX: g++-${{ matrix.gcc }}
    - name: Upload build
      uses: actions/upload-artifact@v4
      with:
        name: soh-linux-${{ matrix.archive-suffix }}
        path: |
          soh.appimage
          readme.txt
  build-windows:
    needs: generate-soh-otr
    runs-on: ${{ (vars.WINDOWS_RUNNER && fromJSON(vars.WINDOWS_RUNNER)) || 'windows-latest' }}
    steps:
    - name: Install dependencies
      if: ${{ !vars.WINDOWS_RUNNER }}
      run: |
        choco install ninja
        Remove-Item -Path "C:\ProgramData\Chocolatey\bin\ccache.exe" -Force -ErrorAction SilentlyContinue
    - name: Debug environment
      run: |
        choco list --local
        ninja --version
        cmake --version
        dir ${{github.workspace}}\vcpkg
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{ runner.os }}-ccache
    - name: Setup vcpkg
      uses: lukka/get-cmake@latest
    - name: Run vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgDirectory: ${{ github.workspace }}/vcpkg
        vcpkgJsonGlob: '**/vcpkg.json'
        vcpkgGitCommitId: 'HEAD'
        doNotCache: false
        vcpkgTriplet: x64-windows-static
        vcpkgArguments: zlib bzip2 libpng sdl2 sdl2-net glew glfw3 boost
    - name: Verify vcpkg
      run: |
        dir ${{github.workspace}}\vcpkg\installed\x64-windows-static
        ${{github.workspace}}\vcpkg\vcpkg list
    - name: Configure Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1
    - name: Build SoH
      env: 
        VCPKG_ROOT: ${{github.workspace}}/vcpkg
      run: |
        set $env:PATH="$env:USERPROFILE/.cargo/bin;$env:PATH"
        cmake -S . -B build-windows -G Ninja -DCMAKE_MAKE_PROGRAM=ninja -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_C_COMPILER_LAUNCHER=ccache -CMAKE_CXX_COMPILER_LAUNCHER=ccache -DBUILD_REMOTE_CONTROL=1 -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/vcpkg/scripts/buildsystems/vcpkg.cmake
        if (-Not (Test-Path build-windows/build.ninja)) { Write-Error "build.ninja not found"; exit 1 }
        cmake --build build-windows --config Release --parallel 10 --verbose
        if (-Not (Test-Path build-windows/soh.exe)) { Write-Error "soh.exe not found"; exit 1 }
        mkdir soh-windows
        mv build-windows/soh.exe soh-windows/soh.exe
        mkdir soh-windows/debug
        mkdir soh-windows/mods
        New-Item soh-windows/mods/custom_otr_files_go_here.txt -type file
        mv build-windows/soh.pdb soh-windows/debug/soh.pdb
        mv README.md soh-windows/readme.txt
        mv build-windows/gamecontrollerdb.txt soh-windows/gamecontrollerdb.txt
        mv build-windows/assets soh-windows
    - name: Download soh.otr
      uses: actions/upload-artifact@v4
      with:
        name: soh.otr
        path: soh-windows
    - name: Upload build
      uses: actions/upload-artifact@v4
      with:
        name: soh-windows
        path: soh-windows